### ISSUE TITLE
error on loading module-oss.so

### ISSUE THREAD

**Issue by xiaohei31** [RediSearch/RSCoordinator#336]
[root@localhost build]# ldd -r module-oss.so
undefined symbol: hiredisAllocFns       (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0)
undefined symbol: redisBufferWrite      (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0)
undefined symbol: redisBufferRead       (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0)
undefined symbol: __redisSetError       (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0)
undefined symbol: redisProcessCallbacks (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0)
undefined symbol: __redisAsyncDisconnect        (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0)
undefined symbol: hiredisAllocFns       (./module-oss.so)
undefined symbol: redisAsyncHandleRead  (./module-oss.so)
undefined symbol: redisAsyncHandleWrite (./module-oss.so)
undefined symbol: freeReplyObject       (./module-oss.so)
undefined symbol: redisSSLContextGetError       (./module-oss.so)
undefined symbol: redisAsyncDisconnect  (./module-oss.so)
undefined symbol: redisCreateSSLContext (./module-oss.so)
undefined symbol: redisAsyncCommand     (./module-oss.so)
undefined symbol: redisAsyncSetConnectCallback  (./module-oss.so)
undefined symbol: hiredisSetAllocators  (./module-oss.so)
undefined symbol: redisAsyncFree        (./module-oss.so)
undefined symbol: redisAsyncConnectWithOptions  (./module-oss.so)
undefined symbol: redisFormatSdsCommandArgv     (./module-oss.so)
undefined symbol: redisAsyncFormattedCommand    (./module-oss.so)
undefined symbol: redisAsyncSetDisconnectCallback       (./module-oss.so)
undefined symbol: redisInitiateSSLWithContext   (./module-oss.so)

how should i fix it ?

**Comment by chenlizhao** [comment]
> [root@localhost build]# ldd -r module-oss.so undefined symbol: hiredisAllocFns (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0) undefined symbol: redisBufferWrite (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0) undefined symbol: redisBufferRead (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0) undefined symbol: __redisSetError (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0) undefined symbol: redisProcessCallbacks (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0) undefined symbol: __redisAsyncDisconnect (/root/software/download/redis/RSCoordinator/build/src/dep/rmr/hiredis/libhiredis_ssl.so.1.0.0) undefined symbol: hiredisAllocFns (./module-oss.so) undefined symbol: redisAsyncHandleRead (./module-oss.so) undefined symbol: redisAsyncHandleWrite (./module-oss.so) undefined symbol: freeReplyObject (./module-oss.so) undefined symbol: redisSSLContextGetError (./module-oss.so) undefined symbol: redisAsyncDisconnect (./module-oss.so) undefined symbol: redisCreateSSLContext (./module-oss.so) undefined symbol: redisAsyncCommand (./module-oss.so) undefined symbol: redisAsyncSetConnectCallback (./module-oss.so) undefined symbol: hiredisSetAllocators (./module-oss.so) undefined symbol: redisAsyncFree (./module-oss.so) undefined symbol: redisAsyncConnectWithOptions (./module-oss.so) undefined symbol: redisFormatSdsCommandArgv (./module-oss.so) undefined symbol: redisAsyncFormattedCommand (./module-oss.so) undefined symbol: redisAsyncSetDisconnectCallback (./module-oss.so) undefined symbol: redisInitiateSSLWithContext (./module-oss.so)
> 
> how should i fix it ?

hi, how do you fix it?

**Comment by chenlizhao** [comment]
I have the same issue

**Comment by chenlizhao** [comment]
@xiaohei31 what java client will you use for RSCoordinator?

**Comment by chenlizhao** [comment]
I fix this issue, but still get error while loading module-oss.so as:
14340:M 27 Jan 2022 13:25:40.915 # Module /opt/git/RSCoordinator/build/module-oss.so initialization failed. Module not loaded
14340:M 27 Jan 2022 13:25:40.915 # Can't load module from /opt/git/RSCoordinator/build/module-oss.so: server aborting
