### ISSUE TITLE
Unable to create module module-oss.so and module-enterprise.so

### ISSUE THREAD

**Issue by rajkaura** [RediSearch/RSCoordinator#342]
I am trying to compile rscoordinator on Ubuntu 20.04 and getting following build errors.
I have tried multiple releases master/2.2/2.0.15 etc.
Can you please suggest a solution for this.
I see all the latest builds are failed with same reason, last successful build was 2 months ago,
Can you check and update

_**Make Error at CMakeLists.txt:4 (INCLUDE):
  INCLUDE could not find requested file:

    src/dep/RediSearch/cmake/redisearch_cflags.cmake

CMake Error at CMakeLists.txt:59 (ADD_SUBDIRECTORY):
  The source directory

    /home/raj/Desktop/New/RSCoordinator/src/dep/RediSearch

  does not contain a CMakeLists.txt file.

CMake Error at src/dep/rmr/CMakeLists.txt:8 (ADD_SUBDIRECTORY):
  The source directory

    /home/raj/Desktop/New/RSCoordinator/src/dep/rmr/hiredis

  does not contain a CMakeLists.txt file.**_

**Comment by chenlizhao** [comment]
did you git clone with --recursive?

**Comment by xiaohei31** [comment]
RSCoordinator is deprecated for RediSearch>=2.2.
RSCoordinator is already merged into RediSearch.
Please try make RediSearch by  `make build COORD=1`

**Comment by rajkaura** [comment]
Thanks for the response , let me try and comeback

**Comment by rajkaura** [comment]
Thanks we are able to proceed.
